package com.example.booktrack

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.example.booktrack.data.local.BookDatabase
import com.example.booktrack.data.local.ReadingSessionDao
import com.example.booktrack.data.local.ReadingSessionEntity
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class ReadingSessionDaoTest {

    private lateinit var db: BookDatabase
    private lateinit var dao: ReadingSessionDao

    @Before
    fun setUp() {
        val context = ApplicationProvider.getApplicationContext<Context>()
        db = Room.inMemoryDatabaseBuilder(context, BookDatabase::class.java)
            .allowMainThreadQueries()
            .build()
        dao = db.readingSessionDao()
    }

    @After
    fun tearDown() {
        db.close()
    }

    private fun session(
        bookKey: String = "/works/OL1W",
        bookTitle: String = "Dune",
        startPage: Int = 10,
        endPage: Int = 50,
        startTimeMs: Long = 1000L,
        endTimeMs: Long = 5000L,
        durationMs: Long = 4000L
    ) = ReadingSessionEntity(
        bookKey = bookKey,
        bookTitle = bookTitle,
        startPage = startPage,
        endPage = endPage,
        startTimeMs = startTimeMs,
        endTimeMs = endTimeMs,
        durationMs = durationMs
    )

    // --- insertSession ---

    @Test
    fun insertSession_returnsAutoGeneratedId() = runTest {
        val id1 = dao.insertSession(session())
        val id2 = dao.insertSession(session())

        assertTrue(id1 > 0)
        assertTrue(id2 > id1)
    }

    @Test
    fun insertSession_storesAllFields() = runTest {
        dao.insertSession(session(startPage = 5, endPage = 100, durationMs = 9000L))

        val sessions = dao.getSessionsForBook("/works/OL1W").first()
        val stored = sessions.first()
        assertEquals(5, stored.startPage)
        assertEquals(100, stored.endPage)
        assertEquals(9000L, stored.durationMs)
        assertEquals("Dune", stored.bookTitle)
    }

    // --- getSessionsForBook ---

    @Test
    fun getSessionsForBook_emptyWhenNoneInserted() = runTest {
        val sessions = dao.getSessionsForBook("/works/OL1W").first()
        assertEquals(emptyList<ReadingSessionEntity>(), sessions)
    }

    @Test
    fun getSessionsForBook_returnsOnlySessionsForGivenKey() = runTest {
        dao.insertSession(session(bookKey = "/works/OL1W", bookTitle = "Dune"))
        dao.insertSession(session(bookKey = "/works/OL2W", bookTitle = "Foundation"))

        val sessions = dao.getSessionsForBook("/works/OL1W").first()
        assertEquals(1, sessions.size)
        assertEquals("Dune", sessions[0].bookTitle)
    }

    @Test
    fun getSessionsForBook_returnsSessionsOrderedByStartTimeMsDesc() = runTest {
        dao.insertSession(session(startTimeMs = 1000L, endTimeMs = 2000L, durationMs = 1000L))
        dao.insertSession(session(startTimeMs = 3000L, endTimeMs = 4000L, durationMs = 1000L))
        dao.insertSession(session(startTimeMs = 2000L, endTimeMs = 3000L, durationMs = 1000L))

        val sessions = dao.getSessionsForBook("/works/OL1W").first()
        assertEquals(3, sessions.size)
        assertEquals(3000L, sessions[0].startTimeMs)
        assertEquals(2000L, sessions[1].startTimeMs)
        assertEquals(1000L, sessions[2].startTimeMs)
    }

    @Test
    fun getSessionsForBook_returnsMultipleSessionsForSameBook() = runTest {
        repeat(3) { i ->
            dao.insertSession(
                session(startPage = i * 10, endPage = i * 10 + 10, startTimeMs = i.toLong() * 1000)
            )
        }

        val sessions = dao.getSessionsForBook("/works/OL1W").first()
        assertEquals(3, sessions.size)
    }

    @Test
    fun getSessionsForBook_idIsAutoGeneratedAndPositive() = runTest {
        dao.insertSession(session())

        val sessions = dao.getSessionsForBook("/works/OL1W").first()
        assertTrue(sessions.first().id > 0)
    }
}
